name: opendj
home: https://github.com/vladk1m0/opendj-helm
engine: gotpl
keywords:
- opendj
version: 4.4.3
description: |
  OpenDJ is an LDAPv3 compliant directory service, which has been developed for the Java platform, providing a high performance, highly available, and secure store for the identities managed by your organization.
maintainers:
  - email: vladkimo@gmail.com
    name: vladkimo
sources:
  - https://github.com/vladk1m0/opendj-helm
