{{- if .Values.useSecurity -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opendj.fullname" . }}
  labels:
    app: {{ template "opendj.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.opendj.rootPassword }}
  rootPassword: {{ .Values.opendj.rootPassword | b64enc | quote }}
  {{- else }}
  rootPassword: ""
  {{- end }}
{{- end -}}